### ISSUE TITLE
Enhance MTD to support a user-configurable amount of temporal smoothing.

### ISSUE THREAD

**Issue by davidfillmore** [NCAR/MET#1084] opened 2018-12-05 16:59 UTC
This feature was requested by a user via MET-Help:
<br/>
<a href="https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=88022">https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=88022</a>
<br/>

<br/>
The temporal smoothing in MTD is hard-coded to be +/- 1 time step. This user would like to have the ability to apply no temporal smoothing in MTD to see how it changes the results.
<br/>

<br/>
More generally, recommend that the amount of temporal smoothing be a configurable item specified as a beginning and ending offset relative to the current time.  For example, the default (existing) setting would be:
<br/>
   conv_time_window = { beg = -1; end = 1; }
<br/>

<br/>
And for no temporal smoothing:
<br/>
   conv_time_window = { beg = 0; end = 0; }
<br/>

<br/>
Or for the last 3 time steps:
<br/>
   conv_time_window = { beg = -3; end = 0; }
<br/>

<br/>

<i>[MET-1084] created by johnhg</i>

**Comment by JohnHalleyGotway** [comment] 2020-01-02 17:12
Closing since this is a duplicate of #1133 which Randy is working on.

**Closed by JohnHalleyGotway** 2020-01-02 17:12 UTC
Labels: component: application code, priority: high
